server:
  port: 8081

spring:
  application:
    name: auth-service
  cloud:
    config:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

openremote:
  auth-url: https://157.90.237.124:8443/auth/realms/mytenant/protocol/openid-connect/token
  client-id: myuser
  client-secret: KQRiw2qEBNtFnquZ9rraTe4i0j7rtTmT
  api-url: https://157.90.237.124:8443/api/mytenant